use std::fs;

fn fetch_conf_path() -> &'static str {
    // FIXME: change this to actually look for the path

    "../config.toml"
}

pub fn fetch_config() -> Config {
    match toml::from_str(match &fs::read_to_string(fetch_conf_path()) {
        Ok(a) => a,
        Err(e) => {
            eprintln!("config file read failed with Error {e}, fallback to default");
            "../config.toml"
        }
    }) {
        Ok(a) => a,
        Err(e) => {
            eprintln!("config deserialisation failed with Error {e}, falling back to default",);
            Config::default()
        }
    }
}

#[derive(serde::Deserialize, Default)]
#[allow(unused)]
pub struct Config {
    /// Directory in which to find data that is generated by the agent
    pub data: String,

    /// Directory to store data generated here i.e codelings + tests that cover those lines
    pub final_data: String,

    /// Directory where the client codebase lives on this system
    pub solutions_dir: String,

    /// File where the entries are stored
    pub entries_file: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_works() {
        let result = 4;
        assert_eq!(result, 4);
    }
}
