pub fn fetch_conf_path() -> &'static str {
    // FIXME: change this to actually look for the path

    let a = "../config.toml";

    a
}

#[derive(serde::Deserialize)]
pub struct Config {
    /// Directory where to find data that is generated by the agent
    pub data: String,

    /// Directory to store data generated here i.e codelings + tests that cover those lines
    pub final_data: String,

    /// Directory where the client codebase lives on this system
    pub solutions_dir: String,

    /// File where the entries are stored
    pub entries_file: String,
}
