[package]
name = "generation-agent"
version = "0.1.0"
edition = "2024"

[dependencies]
text-splitter = { version = "0.32.0", features = ["code"] }
tree-sitter-python = "0.25.0"
walkdir = "2"
config = { path = "../config" }
transformers = "0.0.15"
tokenizers = { version = "0.23.1", features = ["http"] }
candle-core = "0.9"
candle-nn = "0.9"
candle-transformers = "0.9"

hf-hub = "0.4"

fastembed = "5"
anyhow = "1"
serde = "1.0.229"
serde_json = "1.0.151"
faiss = "0.13.0"
tiktoken-rs = "0.12.0"
